highlighter: pygments
paginate: 4
timezone: America/New_York

sass:
  sass_dir: _sass
  style: :compressed

permalink: /:year:month:day-:title

exclude: [".ruby-version", "README.md", "Rakefile", "Gemfile", "Gemfile.lock", "scss", "config.rb", "bower_components", "bower.json", "node_modules", "package.json", "config.ru", "tmp", "Gruntfile.js", "js"]

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Rhode Island Ruby Users Group
description: 
author:
  name: RIRUG
  # email: joe@joealba.com
  github: rirug
  twitter: rirug

# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
production_url : http://rirug.com

